name: Build Distribution

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: npm run build

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Debug build output
        run: |
          echo "Listing contents of the dist directory..."
          ls -la dist/

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/
          retention-days: 30
